### ISSUE TITLE
Can I use Google-style docstrings?

### ISSUE THREAD

**Issue by dhermes** [dhermes/google-resumable-media#2]
The `sphinx-napolean` plugin makes it easy to integrate these into Sphinx and @jonparrott's `sphinx-docstring-typing` also makes it really nice to make docs.

The real reason this question exists is because the entire `google-cloud-python` docstring corpus is written in standard Sphinx, so having Google-style docstrings coexist might be obnoxious / distracting / "other".

**Comment by jonparrott** [comment]
(Ya'll know where I sit on this issue, I'm strongly in favor of napoleon docstrings)

**Comment by lukesneeringer** [comment]
I do not care. Pick one that works well and go with it.
